### ISSUE TITLE
Update Channel snippets and templates

### ISSUE THREAD

**Issue by TomerFi** [open-cluster-management-io/ocm-vscode-extension#26]
Channel CRD can be found [here](https://github.com/open-cluster-management-io/multicloud-operators-channel/blob/main/deploy/crds/apps.open-cluster-management.io_channels_crd.yaml).

Snippets are saved in our [snippets directory](https://github.com/open-cluster-management-io/ocm-vscode-extension/tree/main/snippets).

Templates are saved in our [templates directory](https://github.com/open-cluster-management-io/ocm-vscode-extension/tree/main/templates).

[VSCode Snippet Guide](https://code.visualstudio.com/api/language-extensions/snippet-guide).
[VSCode Using Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets).

Related issue: #21 

> Templates are a part of our _ocmNewProject_ command, no vscode docs available.
> We have multiple templates, each template as its own Channel manifest.

**Comment by ilan-pinto** [comment]
@TomerFi 
I see that the new CRD supports "gates" and "matched labels" which are not mandatory fields. in addition, there are no official doc or examples in the OCM site. 
do you think we need to add them to the snippets?

**Comment by TomerFi** [comment]
Well... we can push PRs to update OCM site too. :-)

Maybe, because these fields aren't mandated and not yet document, we can perhaps do it in another PR so we won't block #63 ?

**Comment by ilan-pinto** [comment]
Of course.  the changes are on another branch

**Comment by ilan-pinto** [comment]
@TomerFi I checked that issue with @mikeshng. the "gates" field is no longer in use, it is there for backward compatibility. 
meaning there are no changes required for snippets or templates.
